export const profile = {
  id: "hello@naver.com",
  password: "1234",
  notice: {
    book: {
      id: "1001",
      title: "배고픔의 미학",
      description: "이러이러한 내용입니다",
      date: "",
      author: "홍길동",
      link: "www.naver.com",
      image: "",
    },
    book: {
      id: "1002",
      title: "배고픔의 미학",
      description: "이러이러한 내용입니다",
      date: "",
      author: "홍길동",
      link: "www.naver.com",
      image: "",
    },
    book: {
      id: "1003",
      title: "배고픔의 미학",
      description: "이러이러한 내용입니다",
      date: "",
      author: "홍길동",
      link: "www.naver.com",
      image: "",
    },
    book: {
      id: "1004",
      title: "배고픔의 미학",
      description: "이러이러한 내용입니다",
      date: "",
      author: "홍길동",
      link: "www.naver.com",
      image: "",
    },
    book: {
      id: "1005",
      title: "배고픔의 미학",
      description: "이러이러한 내용입니다",
      date: "",
      author: "홍길동",
      link: "www.naver.com",
      image: "",
    },
  },
};
